site_name: Vizualizace 3D modelů pomocí moderních technologií (155YV3D)
nav:
  - Charakteristika předmětu: index.md
  - Cvičení:
      - Úloha 1 – Metody vizualizace fotogrammetrických modelů ve virtuální realitě s využitím Unreal Engine: cviceni/cviceni1.md 
      - Úloha 2 - Procedurální modelování: cviceni/cviceni2.md
      - Pokročilejší využití JavaScriptu: cviceni/cviceni3.md
      - Úloha 2 – VS Code, Netlify. Mapová aplikace v prostředí Leaflet: cviceni/cviceni4.md
      - Úloha 3A – Knihovna D3.js: cviceni/cviceni5.md
      - Úloha 3B – Vylepšení aplikace pomocí D3.js – grafy, diagramy, pop-upy: cviceni/cviceni6.md

  # - Data: data.md

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicon.png
  logo: assets/favicon.svg
  icon:
    annotation: material/plus-circle
  features:
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
  language: cs
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: custom
      accent: custom
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: custom
      accent: custom
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/CTUGeomatics
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/geomatics.ctu
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/geomatics.ctu
copyright: <a href="https://geomatics.fsv.cvut.cz" target="_blank">Katedra geomatiky</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;2023-2025
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret
  - pymdownx.tilde

